exports.seed = function (knex) {
	return knex('teams').del()
		.then(function () {
			return knex('teams').insert(

				// data generated by https://mockaroo.com/

				[
					{ "name": "Nitzsche-O'Hara", "description": "Struck by duck", "created_at": "2019-11-02 06:29:22", "updated_at": "2019-05-08 18:54:29" , "organization_id": 1, "team_type":"public"},
					{ "name": "Huels and Sons", "description": "Partial physeal arrest, left distal humerus", "created_at": "2019-07-18 09:44:45", "updated_at": "2019-05-08 18:54:29" , "organization_id": 1, "team_type":"public"},
					{ "name": "Bechtelar-Langworth", "description": "Bullous myringitis, bilateral", "created_at": "2019-12-30 11:39:26", "updated_at": "2019-12-27 19:54:22" , "organization_id": 1, "team_type":"private"},
					{ "name": "Marquardt Inc", "description": "Injury of right internal carotid artery, intracranial portion, not elsewhere classified with loss of consciousness of any duration with death due to brain injury prior to regaining consciousness, sequela", "created_at": "2019-12-23 19:49:31", "updated_at": "2019-10-04 02:23:04" , "organization_id": 1, "team_type":"private"},
					{ "name": "Hane and Sons", "description": "Burn of second degree of multiple right fingers (nail), including thumb, initial encounter", "created_at": "2019-09-24 13:21:49", "updated_at": "2019-08-23 07:52:24" , "organization_id": 1, "team_type":"private"},
					{ "name": "Corwin Group", "description": "Anaplastic large cell lymphoma, ALK-negative, unspecified site", "created_at": "2019-03-20 14:04:43", "updated_at": "2019-10-30 08:32:25" , "organization_id": 1, "team_type":"private"},
					{ "name": "Herzog and Sons", "description": "Congenital malformations of palate, not elsewhere classified", "created_at": "2019-01-27 03:38:07", "updated_at": "2019-08-01 23:55:43" , "organization_id": 1, "team_type":"private"},
					{ "name": "Trantow, Predovic and Beahan", "description": "Myositis ossificans traumatica, lower leg", "created_at": "2019-12-09 02:21:35", "updated_at": "2019-08-13 08:10:44" , "organization_id": 1, "team_type":"private"},
					{ "name": "Mills, Stoltenberg and Leuschke", "description": "Displaced fracture of medial condyle of right tibia, sequela", "created_at": "2019-08-20 20:04:11", "updated_at": "2019-05-02 17:38:17" , "organization_id": 1, "team_type":"private"},
					{ "name": "Casper and Sons", "description": "Hypothermia, not associated with low environmental temperature", "created_at": "2019-01-18 12:53:29", "updated_at": "2019-02-13 19:13:27" , "organization_id": 1, "team_type":"private"},
					{ "name": "Mann and Sons", "description": "Underdosing of other estrogens and progestogens", "created_at": "2019-06-10 12:53:51", "updated_at": "2019-06-30 14:40:08" , "organization_id": 1, "team_type":"private"},
					{ "name": "Metz-Schroeder", "description": "Primary blast injury of lung, unspecified", "created_at": "2019-07-05 13:26:02", "updated_at": "2019-05-31 15:56:14" , "organization_id": 1, "team_type":"private"},
					{ "name": "McClure-Terry", "description": "Drug-induced headache, not elsewhere classified, intractable", "created_at": "2019-02-18 06:47:00", "updated_at": "2019-09-29 03:30:24" , "organization_id": 1, "team_type":"private"},
					{ "name": "Connelly Group", "description": "Other and unspecified asthma", "created_at": "2019-06-16 10:26:32", "updated_at": "2019-06-06 19:49:27" , "organization_id": 1, "team_type":"private"},
					{ "name": "Zboncak-Osinski", "description": "Nondisplaced fracture of head of right radius, subsequent encounter for closed fracture with nonunion", "created_at": "2019-01-03 12:42:02", "updated_at": "2019-05-17 13:27:17" , "organization_id": 1, "team_type":"private"},
					{ "name": "Hahn Inc", "description": "Segmental fracture of shaft of tibia", "created_at": "2019-10-13 03:14:47", "updated_at": "2019-08-25 16:59:01" , "organization_id": 1, "team_type":"private"},
					{ "name": "Kreiger, Langworth and Beatty", "description": "Inflammatory polyps of colon with abscess", "created_at": "2019-10-21 07:58:55", "updated_at": "2019-11-16 17:46:48" , "organization_id": 1, "team_type":"private"},
					{ "name": "Kling Group", "description": "Acute embolism and thrombosis of other specified deep vein of left lower extremity", "created_at": "2019-10-26 18:56:03", "updated_at": "2019-08-05 23:32:57" , "organization_id": 1, "team_type":"private"},
					{ "name": "Fritsch-Buckridge", "description": "Insect bite (nonvenomous) of shoulder", "created_at": "2019-01-09 00:49:07", "updated_at": "2019-03-23 17:09:32" , "organization_id": 1, "team_type":"private"},
					{ "name": "Borer, Nienow and Kunde", "description": "Insect bite (nonvenomous) of unspecified shoulder, sequela", "created_at": "2019-01-30 10:29:39", "updated_at": "2019-10-14 18:46:29","organization_id":1 , "team_type":"private"}
				]);
		});
};
