exports.seed = function (knex) {
	return knex('roles').truncate()
		.then(function () {
			return knex('roles').insert(

				// data generated by https://mockaroo.com/

				[
					{
						"name": "Bitwolf"
					}, {
						"name": "Toughjoyfax"
					}, {
						"name": "Opela"
					}
				]
			);
		});
};
